version: "3.8"

services:
  db:
    image: postgres:14.4-alpine3.16
    env_file:
      - ./docker/env.db

  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: "./manage.py runserver 0.0.0.0:80"
    env_file:
      - ./docker/env.db
    container_name: app
    ports:
      - "80:80"
    volumes:
      - .:/opt/code
    depends_on:
      - db